primero:
	pandoc -t pdf --metadata-file=meta.yaml primero.md -o TrabajoEscritoAaronDanielAnthony.pdf

segundo:
	pandoc -t pdf --metadata-file=meta-2.yaml segundo.md -o TrabajoEscritoAaronDanielAnthonySegundaEntrega.pdf
